import discrete_approximations_optimal_control_foundation_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace discrete_approximations_optimal_control_foundation_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end discrete_approximations_optimal_control_foundation_canonical_lane_mathlib
end HautevilleHouse
